"""Added account table

Revision ID: 98c9c93ed6a1
Revises:
Create Date: 2022-08-28 14:52:21.631925

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '98c9c93ed6a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
